terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.1.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.35.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
  # The kubectl/kubernetes/helm providers below are layer-specific and stay here.
}

module "guardrails" {
  source = "../../modules/guardrails"

  environment                 = var.environment
  project                     = var.project
  sizing                      = var.sizing
  allowed_public_access_cidrs = var.allowed_public_access_cidrs
  auth_provider               = var.auth_provider
  observability               = var.observability
}

# modules/otel is a sibling of modules/k8s-and-helm, so it does not inherit the
# provider configuration declared inside that module. The cluster-facing providers
# are therefore configured here, at the root.
provider "kubectl" {
  host                   = var.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_ca)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name]
  }
}

provider "kubernetes" {
  host                   = var.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_ca)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name]
  }
}

provider "helm" {
  kubernetes = {
    host                   = var.cluster_endpoint
    cluster_ca_certificate = base64decode(var.cluster_ca)

    exec = {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", var.cluster_name]
    }
  }
}

module "k8s" {
  source = "../../modules/k8s-and-helm"

  cluster_name     = var.cluster_name
  cluster_endpoint = var.cluster_endpoint
  cluster_ca       = var.cluster_ca
  eks_node_group   = var.eks_node_group

  vpc_id = var.vpc_id
  region = var.region

  karpenter_interruption_queue_name = var.karpenter_interruption_queue_name

  auth_provider        = var.auth_provider
  keycloak_db_endpoint = var.keycloak_db_endpoint
  keycloak_hostname    = var.keycloak_hostname

  auth0_issuer        = var.auth0_issuer
  auth0_client_id     = var.auth0_client_id
  auth0_client_secret = var.auth0_client_secret

  observability = var.observability
}

# The OTel collector provisions `aws_eks_addon` and `kubectl_manifest` resources,
# so it needs live cluster credentials and belongs here rather than in the
# observability layer, which is pure AWS.
module "otel" {
  source = "../../modules/otel"

  cluster_name                 = var.cluster_name
  otel_collector_irsa_role_arn = var.otel_collector_irsa_role_arn
  prometheus_endpoint          = var.prometheus_endpoint
  opensearch_endpoint          = var.opensearch_endpoint

  opensearch_username = var.opensearch_master_username
  opensearch_password = var.opensearch_master_password

  region        = var.region
  observability = var.observability

  depends_on = [module.k8s]
}
