terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}

module "guardrails" {
  source = "../../modules/guardrails"

  environment                 = var.environment
  project                     = var.project
  sizing                      = var.sizing
  allowed_public_access_cidrs = var.allowed_public_access_cidrs
  auth_provider               = var.auth_provider
  observability               = var.observability
}

locals {
  cluster_name = var.cluster_name
}

# The node security group straddles the platform/data boundary: EKS needs it at
# creation time, and every data-tier SG references it as an ingress source. It is
# created here and exported, so 20-data depends on 10-platform and not vice versa.
module "node_security_group" {
  source = "../../modules/node-security-group"

  cluster_name = local.cluster_name
  vpc_id       = var.vpc_id
  vpc_cidr     = var.vpc_cidr
  tags         = module.guardrails.common_tags
}

module "iam" {
  source = "../../modules/iam"

  cluster_name = local.cluster_name
}

module "eks" {
  source = "../../modules/eks"

  cluster_name       = local.cluster_name
  kubernetes_version = var.kubernetes_version

  vpc_id          = var.vpc_id
  private_subnets = var.private_subnets

  enable_public_access = module.guardrails.security.eks_endpoint_public_access
  # When public access is on (dev), scope it to the guardrails allow-list rather
  # than the module default of 0.0.0.0/0. Ignored when the endpoint is private.
  endpoint_public_access_cidrs = length(var.allowed_public_access_cidrs) > 0 ? var.allowed_public_access_cidrs : ["0.0.0.0/0"]

  kms_key_arn      = var.kms_key_arn
  eks_nodes_sg_id  = module.node_security_group.security_group_id
  ebs_csi_role_arn = module.iam.ebs_csi_role_arn

  # Cluster admin is granted via access entries (AmazonEKSClusterAdminPolicy),
  # not the creator-admin bootstrap flag. The caller role is always an admin;
  # add break-glass / platform-admin role ARNs here.
  cluster_admin_principal_arns = var.cluster_admin_principal_arns

  # The EKS module takes a single instance type; guardrails hands out a list so a
  # future migration to a mixed-instance node group needs no interface change.
  node_instance_type = module.guardrails.sizing.eks_node_instance_types[0]
  desired_size       = module.guardrails.sizing.eks_node_desired_size
  min_size           = module.guardrails.sizing.eks_node_min_size
  max_size           = module.guardrails.sizing.eks_node_max_size

  tags = module.guardrails.common_tags
}

resource "aws_eks_access_entry" "karpenter_node" {
  cluster_name  = module.eks.eks_cluster_name
  principal_arn = module.iam.karpenter_node_role_arn
  type          = "EC2_LINUX"
}

locals {
  pod_identity_associations = {
    cert_manager = {
      namespace = "cert-manager"
      sa_name   = "cert-manager"
      role_arn  = module.iam.cert_manager_irsa_role_arn
    }
    external_dns = {
      namespace = "external-dns"
      sa_name   = "external-dns"
      role_arn  = module.iam.external_dns_irsa_role_arn
    }
    external_secrets = {
      namespace = "external-secrets"
      sa_name   = "external-secrets"
      role_arn  = module.iam.external_secrets_irsa_role_arn
    }
    aws_lb_controller = {
      namespace = "kube-system"
      sa_name   = "aws-load-balancer-controller"
      role_arn  = module.iam.aws_lb_controller_irsa_role_arn
    }
    karpenter = {
      namespace = "kube-system"
      sa_name   = "karpenter"
      role_arn  = module.iam.karpenter_irsa_role_arn
    }
    ebs_csi_controller = {
      namespace = "kube-system"
      sa_name   = "ebs-csi-controller-sa"
      role_arn  = module.iam.ebs_csi_role_arn
    }
  }
}

resource "aws_eks_pod_identity_association" "this" {
  for_each = local.pod_identity_associations

  cluster_name    = module.eks.eks_cluster_name
  namespace       = each.value.namespace
  service_account = each.value.sa_name
  role_arn        = each.value.role_arn
}

resource "terraform_data" "platform_invariants" {
  input = var.environment

  lifecycle {
    # A private-only endpoint with no Verified Access instance in 30-edge leaves
    # the control plane unreachable. Guardrails enforces the pairing; this asserts
    # the platform layer agrees with it.
    precondition {
      condition     = module.guardrails.security.eks_endpoint_public_access || module.guardrails.security.verified_access_enabled
      error_message = "EKS endpoint is private-only but Verified Access is disabled: the API would be unreachable."
    }
  }
}
