terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.9.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}

module "guardrails" {
  source = "../../modules/guardrails"

  environment                 = var.environment
  project                     = var.project
  sizing                      = var.sizing
  allowed_public_access_cidrs = var.allowed_public_access_cidrs
  auth_provider               = var.auth_provider
  observability               = var.observability
}

locals {
  security = module.guardrails.security
  sizing   = module.guardrails.sizing
  tags     = module.guardrails.common_tags

  # MSK places one broker per client subnet and requires the broker count to be an
  # exact multiple of the subnet count.
  msk_subnets = slice(var.private_subnets, 0, local.sizing.msk_broker_count)

  # Posture shared by every database in this layer.
  rds_common = {
    instance_class               = local.sizing.rds_instance_class
    allocated_storage            = local.sizing.rds_allocated_storage
    subnet_ids                   = var.private_subnets
    rds_sg_id                    = module.data_security_groups.rds_sg_id
    kms_key_arn                  = var.kms_key_arn
    port                         = "5432"
    multi_az                     = local.security.rds_multi_az
    storage_encrypted            = local.security.rds_storage_encrypted
    publicly_accessible          = local.security.rds_publicly_accessible
    backup_retention_days        = local.security.rds_backup_retention_days
    deletion_protection          = local.security.rds_deletion_protection
    iam_database_authentication  = local.security.rds_iam_database_auth
    performance_insights_enabled = local.security.rds_performance_insights
    copy_tags_to_snapshot        = local.security.rds_copy_tags_to_snapshot
    skip_final_snapshot          = local.security.rds_skip_final_snapshot
  }

  databases = merge(
    {
      subscription = { name = "saas-subscription-db", db_name = "subscription_db", db_username = "subscription_user", password = var.subscription_db_password }
      billing      = { name = "saas-billing-db", db_name = "billing_db", db_username = "billing_user", password = var.billing_db_password }
      usage        = { name = "saas-usage-db", db_name = "usage_db", db_username = "usage_user", password = var.usage_db_password }
    },
    var.auth_provider == "auth-service" ? {
      auth = { name = "saas-auth-db", db_name = "auth_db", db_username = "auth_user", password = var.auth_db_password }
    } : {},
    var.auth_provider == "keycloak" ? {
      keycloak = { name = "keycloak-db", db_name = "keycloak_db", db_username = "keycloak_user", password = var.keycloak_db_password }
    } : {},
  )
}

module "data_security_groups" {
  source = "../../modules/data-security-groups"

  cluster_name    = var.cluster_name
  vpc_id          = var.vpc_id
  eks_nodes_sg_id = var.eks_nodes_sg_id

  msk_sasl_iam_enabled   = local.security.msk_sasl_iam_enabled
  msk_sasl_scram_enabled = local.security.msk_sasl_scram_enabled

  tags = local.tags
}

module "rds" {
  source   = "../../modules/rds"
  for_each = local.databases

  name        = each.value.name
  db_name     = each.value.db_name
  db_username = each.value.db_username
  db_password = each.value.password

  instance_class               = local.rds_common.instance_class
  allocated_storage            = local.rds_common.allocated_storage
  subnet_ids                   = local.rds_common.subnet_ids
  rds_sg_id                    = local.rds_common.rds_sg_id
  kms_key_arn                  = local.rds_common.kms_key_arn
  port                         = local.rds_common.port
  multi_az                     = local.rds_common.multi_az
  storage_encrypted            = local.rds_common.storage_encrypted
  publicly_accessible          = local.rds_common.publicly_accessible
  backup_retention_days        = local.rds_common.backup_retention_days
  deletion_protection          = local.rds_common.deletion_protection
  iam_database_authentication  = local.rds_common.iam_database_authentication
  performance_insights_enabled = local.rds_common.performance_insights_enabled
  copy_tags_to_snapshot        = local.rds_common.copy_tags_to_snapshot
  skip_final_snapshot          = local.rds_common.skip_final_snapshot

  tags = local.tags
}

module "elasticache" {
  source = "../../modules/elasticache"

  name        = "saas-redis"
  subnet_ids  = var.private_subnets
  redis_sg_id = module.data_security_groups.redis_sg_id
  kms_key_arn = var.kms_key_arn

  node_type                  = local.sizing.elasticache_node_type
  num_replicas               = local.sizing.elasticache_num_replicas
  at_rest_encryption_enabled = local.security.elasticache_at_rest_encryption
  transit_encryption_enabled = local.security.elasticache_transit_encryption
  auth_token_enabled         = local.security.elasticache_auth_token_enabled
  automatic_failover_enabled = local.security.elasticache_automatic_failover
  multi_az_enabled           = local.security.elasticache_multi_az
  snapshot_retention_days    = local.security.elasticache_snapshot_retention_days

  tags = local.tags
}

module "msk" {
  source = "../../modules/msk"

  cluster_name = "saas-msk"
  subnet_ids   = local.msk_subnets
  msk_sg_id    = module.data_security_groups.msk_sg_id
  kms_key_arn  = var.kms_key_arn

  number_of_broker_nodes = local.sizing.msk_broker_count
  broker_instance_type   = local.sizing.msk_broker_instance_type

  unauthenticated_access   = local.security.msk_unauthenticated_access
  sasl_iam_enabled         = local.security.msk_sasl_iam_enabled
  sasl_scram_enabled       = local.security.msk_sasl_scram_enabled
  client_broker_encryption = local.security.msk_client_broker_encryption
  in_cluster_encryption    = local.security.msk_in_cluster_encryption
  enhanced_monitoring      = local.security.msk_enhanced_monitoring

  tags = local.tags
}

resource "terraform_data" "data_invariants" {
  input = var.environment

  lifecycle {
    precondition {
      condition     = local.sizing.msk_broker_count % length(local.msk_subnets) == 0
      error_message = "MSK broker count must be an exact multiple of the client subnet count."
    }

    precondition {
      condition     = length(var.private_subnets) >= local.sizing.msk_broker_count
      error_message = "Not enough private subnets to place one MSK broker per subnet."
    }
  }
}
