variable "project" {
  description = "Project slug. Drives tags and the guardrails name prefix."
  type        = string
  default     = "saas"
}

variable "environment" {
  description = "dev | staging | prod. Selects the entire security posture."
  type        = string
}

variable "region" {
  description = "AWS region."
  type        = string
  default     = "us-east-1"
}

variable "capacity_tier" {
  description = "Named capacity/scale tier (cost only). Passed through to guardrails; null => the env's default rung."
  type        = string
  default     = null
}

variable "sizing" {
  description = "Per-environment sizing overrides. Cost/capacity only."
  type = object({
    rds_instance_class        = optional(string)
    rds_allocated_storage     = optional(number)
    msk_broker_instance_type  = optional(string)
    msk_broker_count          = optional(number)
    elasticache_node_type     = optional(string)
    elasticache_num_replicas  = optional(number)
    opensearch_instance_type  = optional(string)
    opensearch_instance_count = optional(number)
    opensearch_volume_size    = optional(number)
    eks_node_instance_types   = optional(list(string))
    eks_node_min_size         = optional(number)
    eks_node_max_size         = optional(number)
    eks_node_desired_size     = optional(number)
  })
  default = {}
}

variable "allowed_public_access_cidrs" {
  description = "CIDRs permitted to reach the EKS public API endpoint (dev only)."
  type        = list(string)
  default     = []
}

variable "auth_provider" {
  description = "keycloak | auth-service"
  type        = string
  default     = "keycloak"
}

variable "observability" {
  description = "Subset of [elk, grafana] — self-hosted observability stacks this cluster runs."
  type        = list(string)
  default     = ["elk"]
}

# DB master passwords are generated by modules/rds and stored in Secrets Manager
# (password = null in the databases map). They are intentionally NOT variables —
# no secret is passed from CI.

# ── Inputs supplied by Terragrunt dependency blocks ──────────────────────────
# From 00-network:
variable "cluster_name" { type = string }
variable "vpc_id" { type = string }
variable "private_subnets" { type = list(string) }
variable "kms_key_arn" { type = string }

# From 10-platform:
variable "eks_nodes_sg_id" {
  description = "EKS node SG; the sole permitted ingress source for the data tier."
  type        = string
}
variable "karpenter_interruption_queue_name" {
  description = "SQS interruption queue name; surfaced to the CD repo via the gitops_contract cluster block."
  type        = string
  default     = ""
}
