terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = ">= 4.0.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}


locals {
  name = "${var.project}-${var.environment}"

  # Env-derived GitHub contexts (overridable). The protected Environment that
  # gates the cluster-bootstrap role defaults to the env name; the apply role
  # trusts that same Environment's deployments.
  bootstrap_environment = var.bootstrap_environment != "" ? var.bootstrap_environment : var.environment
  apply_environments    = length(var.apply_environments) > 0 ? var.apply_environments : [var.environment]

  tags = {
    Project     = var.project
    Environment = var.environment
    Component   = "bootstrap"
    ManagedBy   = "terraform"
  }
}

# Cluster-facing provider, configured from the platform layer's remote state
# (same exec-auth pattern as the addons layer). Used to apply the ci-deployer RBAC.
provider "kubectl" {
  host                   = var.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_ca)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name]
  }
}

# ── Per-env toolchain image repository ───────────────────────────────────────
module "ecr" {
  source = "../../modules/bootstrap-ecr"

  repository_name = "${local.name}-bootstrap-runner"
  kms_key_arn     = var.kms_key_arn
  tags            = local.tags
}

# ── Keyless, scoped CI roles (plan / apply / gated cluster-bootstrap) ─────────
module "oidc" {
  source = "../../modules/gha-oidc"

  name                  = local.name
  environment           = var.environment
  github_owner          = var.github_owner
  github_repo           = var.github_repo
  default_branch        = var.default_branch
  apply_environments    = local.apply_environments
  bootstrap_environment = local.bootstrap_environment
  create_oidc_provider  = var.create_oidc_provider
  oidc_provider_arn     = var.oidc_provider_arn
  state_bucket          = var.state_bucket
  apply_managed_policy  = var.apply_managed_policy
  tags                  = local.tags
}

module "runner" {
  source = "../../modules/gha-runner"

  name               = local.name
  vpc_id             = var.vpc_id
  subnet_ids         = var.private_subnets
  github_owner       = var.github_owner
  github_repo        = var.github_repo
  runner_labels      = var.runner_labels
  instance_type      = var.runner_instance_type
  runner_version     = var.runner_version
  ecr_repository_arn = module.ecr.repository_arn
  ecr_registry       = split("/", module.ecr.repository_url)[0]
  kms_key_arn        = var.kms_key_arn
  tags               = local.tags
}

# ===========================================================================
# EKS access entries — the least-privilege split.
#
#  1. cluster-bootstrap role -> cluster-admin (the ONLY cluster-admin principal
#     besides the human bootstrapper). Gated: assumable solely from the protected
#     bootstrap Environment. This is what lets CI (re)apply the escalation-capable
#     ci-deployer RBAC without any standing admin.
#  2. tf-apply role -> STANDARD entry mapped to the ci-deployers K8s group. Its
#     actual authorization is the ci-deployer RBAC below — never cluster-admin.
# ===========================================================================
resource "aws_eks_access_entry" "cluster_bootstrap" {
  count = var.create_gated_admin_access_entry ? 1 : 0

  cluster_name  = var.cluster_name
  principal_arn = module.oidc.cluster_bootstrap_role_arn
  type          = "STANDARD"
  tags          = local.tags
}

resource "aws_eks_access_policy_association" "cluster_bootstrap_admin" {
  count = var.create_gated_admin_access_entry ? 1 : 0

  cluster_name  = var.cluster_name
  principal_arn = module.oidc.cluster_bootstrap_role_arn
  policy_arn    = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"

  access_scope {
    type = "cluster"
  }

  depends_on = [aws_eks_access_entry.cluster_bootstrap]
}

resource "aws_eks_access_entry" "deployer" {
  count = var.map_deployer_access_entry ? 1 : 0

  cluster_name      = var.cluster_name
  principal_arn     = module.oidc.tf_apply_role_arn
  type              = "STANDARD"
  kubernetes_groups = [var.deployer_group]
  tags              = local.tags
}

module "ci_deployer_rbac" {
  source = "../../modules/ci-deployer-rbac"
  count  = var.manage_ci_deployer_rbac ? 1 : 0

  manifest_path  = abspath("${path.module}/rbac/ci-deployer.yaml.tpl")
  deployer_group = var.deployer_group

  depends_on = [aws_eks_access_policy_association.cluster_bootstrap_admin]
}

resource "terraform_data" "bootstrap_invariants" {
  input = var.environment

  lifecycle {
    precondition {
      condition     = local.bootstrap_environment != ""
      error_message = "bootstrap_environment must resolve to a protected GitHub Environment; the cluster-bootstrap role trusts nothing else."
    }
    precondition {
      condition     = !var.map_deployer_access_entry || var.deployer_group != ""
      error_message = "deployer_group is required when mapping the tf-apply access entry to a Kubernetes group."
    }
  }
}
