terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = ">= 4.0.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}


data "aws_caller_identity" "current" {}
data "aws_partition" "current" {}

locals {
  name = "${var.project}-${var.environment}"

  # Env-derived GitHub contexts (overridable). The protected Environment that
  # gates the cluster-bootstrap role defaults to the env name; the apply role
  # trusts that same Environment's deployments.
  bootstrap_environment = var.bootstrap_environment != "" ? var.bootstrap_environment : var.environment
  apply_environments    = length(var.apply_environments) > 0 ? var.apply_environments : [var.environment]

  # The GitHub Actions OIDC provider URL is fixed, so its ARN is fully determined
  # by the account. When this env does NOT create the provider (second+ env of a
  # shared account), derive the existing ARN automatically so no ARN has to be
  # copied between envs — an explicit var.oidc_provider_arn still wins if set.
  github_oidc_provider_arn = var.create_oidc_provider ? "" : (
    var.oidc_provider_arn != "" ? var.oidc_provider_arn :
    "arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/token.actions.githubusercontent.com"
  )

  tags = {
    Project     = var.project
    Environment = var.environment
    Component   = "bootstrap"
    ManagedBy   = "terraform"
  }
}

# ── Dedicated CMK ────────────────────────────────────────────────────────────
# bootstrap owns its own key so the layer has ZERO dependency on 00-network and
# can be applied first. Encrypts the toolchain ECR repo.
resource "aws_kms_key" "bootstrap" {
  description             = "${local.name} bootstrap (ECR toolchain) encryption"
  deletion_window_in_days = 30
  enable_key_rotation     = true
  tags                    = local.tags
}

resource "aws_kms_alias" "bootstrap" {
  name          = "alias/${local.name}-bootstrap"
  target_key_id = aws_kms_key.bootstrap.key_id
}

# ── Per-env toolchain image repository ───────────────────────────────────────
module "ecr" {
  source = "../../modules/bootstrap-ecr"

  repository_name = "${local.name}-bootstrap-runner"
  kms_key_arn     = aws_kms_key.bootstrap.arn
  tags            = local.tags
}

# ── Keyless, scoped CI roles (plan / apply / gated cluster-bootstrap) ─────────
module "oidc" {
  source = "../../modules/gha-oidc"

  name                  = local.name
  environment           = var.environment
  github_owner          = var.github_owner
  github_repo           = var.github_repo
  default_branch        = var.default_branch
  apply_environments    = local.apply_environments
  bootstrap_environment = local.bootstrap_environment
  create_oidc_provider  = var.create_oidc_provider
  oidc_provider_arn     = local.github_oidc_provider_arn
  state_bucket          = var.state_bucket
  apply_managed_policy  = var.apply_managed_policy
  tags                  = local.tags
}

resource "terraform_data" "bootstrap_invariants" {
  input = var.environment

  lifecycle {
    precondition {
      condition     = local.bootstrap_environment != ""
      error_message = "bootstrap_environment must resolve to a protected GitHub Environment; the cluster-bootstrap role trusts nothing else."
    }
  }
}
