terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}

# Single ECR registry layer: owns one repository per microservice image for the
# whole env, independent of the VPC (00-network) and cluster (10-platform)
# lifecycles. Services push here and pods pull from here; nothing in this layer
# is coupled to a specific service's state. Posture (scan/immutable/KMS) comes
# from guardrails so it tracks the same security contract as the rest of the env.
module "guardrails" {
  source = "../../modules/guardrails"

  environment                 = var.environment
  project                     = var.project
  sizing                      = var.sizing
  capacity_tier               = var.capacity_tier
  allowed_public_access_cidrs = var.allowed_public_access_cidrs
  auth_provider               = var.auth_provider
  observability               = var.observability
}

locals {
  security = module.guardrails.security
  tags     = module.guardrails.common_tags
}

# Dedicated CMK for the registry so the ECR layer carries no dependency on
# 00-network. Only created when guardrails requires KMS encryption; otherwise the
# repositories fall back to ECR-managed AES256 and no key is provisioned.
module "kms" {
  source = "../../modules/kms"
  count  = local.security.ecr_kms_encryption ? 1 : 0

  description             = "${var.project}-${var.environment} ECR registry encryption"
  alias                   = "alias/${var.project}-${var.environment}-ecr"
  deletion_window_in_days = local.security.kms_deletion_window_days
  enable_key_rotation     = local.security.kms_key_rotation

  tags = local.tags
}

module "ecr" {
  source = "../../modules/ecr"

  # Microservice images plus the Crossplane composition function packages. Both
  # share the registry's posture; the function repo names must match what the
  # build-function workflow pushes to (<registry>/<function>).
  repositories   = concat(var.services, var.functions)
  immutable_tags = local.security.ecr_immutable_tags
  scan_on_push   = local.security.ecr_scan_on_push
  kms_encryption = local.security.ecr_kms_encryption
  kms_key_arn    = local.security.ecr_kms_encryption ? module.kms[0].key_arn : ""

  tags = local.tags
}

# ── Helm OCI chart repos: auto-created on first `helm push` ──────────────────
# The microservices ApplicationSet (CD repo) pulls charts from
# oci://<registry>/helm and the service catalogue is auto-discovered from
# charts/*, so the set of helm/<chart> repos is open-ended. ECR does not create
# repositories on a plain push, so a registry creation template materialises any
# helm/* repo on first push with the same posture as the image repos — no edit
# here when a new chart is added. The template is registry-scoped (one per
# account+region); each env is its own account, so per-env management is safe.
#
# A custom role is mandatory because the template sets KMS encryption + tags:
# ECR assumes it to create the repository, put its lifecycle policy and tag it.
data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "ecr_template_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ecr.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "ecr_template" {
  name               = "${var.project}-${var.environment}-ecr-helm-template"
  assume_role_policy = data.aws_iam_policy_document.ecr_template_assume.json
  tags               = local.tags
}

data "aws_iam_policy_document" "ecr_template" {
  statement {
    sid    = "CreateHelmChartRepos"
    effect = "Allow"
    actions = [
      "ecr:CreateRepository",
      "ecr:PutLifecyclePolicy",
      "ecr:TagResource",
    ]
    resources = ["arn:aws:ecr:${var.region}:${data.aws_caller_identity.current.account_id}:repository/helm/*"]
  }

  dynamic "statement" {
    for_each = local.security.ecr_kms_encryption ? [1] : []
    content {
      sid       = "UseRegistryCmk"
      effect    = "Allow"
      actions   = ["kms:DescribeKey", "kms:CreateGrant"]
      resources = [module.kms[0].key_arn]
    }
  }
}

resource "aws_iam_role_policy" "ecr_template" {
  name   = "${var.project}-${var.environment}-ecr-helm-template"
  role   = aws_iam_role.ecr_template.id
  policy = data.aws_iam_policy_document.ecr_template.json
}

resource "aws_ecr_repository_creation_template" "helm" {
  # "helm" matches repositories pushed as helm/<chart> (ECR appends the trailing /).
  prefix               = "helm"
  applied_for          = ["CREATE_ON_PUSH"]
  image_tag_mutability = local.security.ecr_immutable_tags ? "IMMUTABLE" : "MUTABLE"
  custom_role_arn      = aws_iam_role.ecr_template.arn
  resource_tags        = local.tags

  encryption_configuration {
    encryption_type = local.security.ecr_kms_encryption ? "KMS" : "AES256"
    kms_key         = local.security.ecr_kms_encryption ? module.kms[0].key_arn : null
  }

  lifecycle_policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep only the most recent 10 chart versions"
        selection = {
          tagStatus   = "any"
          countType   = "imageCountMoreThan"
          countNumber = 10
        }
        action = { type = "expire" }
      },
    ]
  })
}
