terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
  }
  # Backend and the aws provider (incl. default_tags) are generated by Terragrunt
  # from the root terragrunt.hcl. This root is consumed only through live/<env>/.
}

module "guardrails" {
  source = "../../modules/guardrails"

  environment                 = var.environment
  project                     = var.project
  sizing                      = var.sizing
  allowed_public_access_cidrs = var.allowed_public_access_cidrs
  auth_provider               = var.auth_provider
  observability               = var.observability
}

data "aws_availability_zones" "available" {
  state = "available"
}

locals {
  # The VPC module maps subnet[i] onto azs[i], so the AZ list must be exactly as
  # long as the subnet list. Passing the full account AZ list also silently
  # inflates the NAT gateway count when one_nat_gateway_per_az is set.
  az_count = max(length(var.private_subnets), length(var.public_subnets))
  azs      = slice(data.aws_availability_zones.available.names, 0, local.az_count)

  ordered_public_subnets  = sort(var.public_subnets)
  ordered_private_subnets = sort(var.private_subnets)

  services = ["api-gateway", "auth-service", "subscription-service", "billing-service", "usage-service"]
}

resource "aws_kms_key" "main" {
  description             = "Shared KMS key for ${var.cluster_name} encryption"
  deletion_window_in_days = module.guardrails.security.kms_deletion_window_days
  enable_key_rotation     = module.guardrails.security.kms_key_rotation

  tags = { Name = "${var.cluster_name}-kms" }
}

resource "aws_kms_alias" "main" {
  name          = "alias/${var.cluster_name}"
  target_key_id = aws_kms_key.main.key_id
}

# Without this, `kms_key_id` on a CloudWatch log group fails: the Logs service
# principal has no grant on the key, and AWS rejects the association.
resource "aws_kms_key_policy" "main" {
  key_id = aws_kms_key.main.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "EnableIAMUserPermissions"
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root" }
        Action    = "kms:*"
        Resource  = "*"
      },
      {
        Sid       = "AllowCloudWatchLogs"
        Effect    = "Allow"
        Principal = { Service = "logs.${var.region}.amazonaws.com" }
        Action = [
          "kms:Encrypt",
          "kms:Decrypt",
          "kms:ReEncrypt*",
          "kms:GenerateDataKey*",
          "kms:DescribeKey",
        ]
        Resource = "*"
        Condition = {
          ArnLike = {
            "kms:EncryptionContext:aws:logs:arn" = "arn:aws:logs:${var.region}:${data.aws_caller_identity.current.account_id}:log-group:*"
          }
        }
      },
    ]
  })
}

# ─── VPC flow logs ───────────────────────────────────────────────────────────

resource "aws_cloudwatch_log_group" "vpc_flow_logs" {
  name              = "/aws/vpc/${var.cluster_name}-flow-logs"
  retention_in_days = module.guardrails.security.vpc_flow_log_retention_days
  kms_key_id        = aws_kms_key.main.arn
}

resource "aws_iam_role" "vpc_flow_log" {
  name = "${var.cluster_name}-vpc-flow-log-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "vpc-flow-logs.amazonaws.com" }
      Action    = "sts:AssumeRole"
      Condition = {
        StringEquals = { "aws:SourceAccount" = data.aws_caller_identity.current.account_id }
      }
    }]
  })
}

data "aws_caller_identity" "current" {}

# Scoped to the flow log group rather than "*". The Describe* actions are not
# resource-scopable and are separated out.
resource "aws_iam_role_policy" "vpc_flow_log" {
  name = "${var.cluster_name}-vpc-flow-log-policy"
  role = aws_iam_role.vpc_flow_log.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ]
        Resource = "${aws_cloudwatch_log_group.vpc_flow_logs.arn}:*"
      },
      {
        Effect   = "Allow"
        Action   = ["logs:DescribeLogGroups", "logs:DescribeLogStreams"]
        Resource = "*"
      },
    ]
  })
}


module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "6.6.1"

  name                 = "${var.cluster_name}-vpc"
  cidr                 = var.vpc_cidr
  azs                  = local.azs
  public_subnets       = local.ordered_public_subnets
  private_subnets      = local.ordered_private_subnets
  enable_nat_gateway   = true
  single_nat_gateway   = module.guardrails.security.vpc_single_nat_gateway
  enable_dns_hostnames = true
  enable_dns_support   = true

  one_nat_gateway_per_az = !module.guardrails.security.vpc_single_nat_gateway

  enable_flow_log                  = module.guardrails.security.vpc_flow_logs_enabled
  flow_log_destination_type        = "cloud-watch-logs"
  flow_log_destination_arn         = aws_cloudwatch_log_group.vpc_flow_logs.arn
  flow_log_cloudwatch_iam_role_arn = aws_iam_role.vpc_flow_log.arn
  flow_log_traffic_type            = module.guardrails.security.vpc_flow_logs_traffic_type

  public_subnet_tags = {
    "kubernetes.io/role/elb"                    = "1"
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
  }

  private_subnet_tags = {
    "kubernetes.io/role/internal-elb"           = "1"
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "karpenter.sh/discovery"                    = var.cluster_name
  }

  tags = { Name = "${var.cluster_name}-vpc" }
}

resource "aws_ecr_repository" "services" {
  for_each = toset(local.services)

  name                 = each.key
  image_tag_mutability = module.guardrails.security.ecr_immutable_tags ? "IMMUTABLE" : "MUTABLE"

  image_scanning_configuration {
    scan_on_push = module.guardrails.security.ecr_scan_on_push
  }

  encryption_configuration {
    encryption_type = module.guardrails.security.ecr_kms_encryption ? "KMS" : "AES256"
    kms_key         = module.guardrails.security.ecr_kms_encryption ? aws_kms_key.main.arn : null
  }

  tags = { Name = each.key }
}

resource "aws_glue_registry" "schema_registry" {
  registry_name = var.schema_registry_name
}

resource "terraform_data" "network_invariants" {
  input = var.environment

  lifecycle {
    precondition {
      condition     = length(var.private_subnets) >= module.guardrails.sizing.msk_broker_count
      error_message = "private_subnets must provide at least one subnet per MSK broker (${module.guardrails.sizing.msk_broker_count} required)."
    }

    precondition {
      condition     = length(var.private_subnets) >= 2
      error_message = "At least two private subnets are required; a single-AZ data tier is not survivable."
    }

    precondition {
      condition     = local.az_count <= length(data.aws_availability_zones.available.names)
      error_message = "More subnets requested than the region has availability zones."
    }
  }
}
