terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}

module "guardrails" {
  source = "../../modules/guardrails"

  environment                 = var.environment
  project                     = var.project
  sizing                      = var.sizing
  allowed_public_access_cidrs = var.allowed_public_access_cidrs
  auth_provider               = var.auth_provider
  observability               = var.observability
}

# Pure AWS: managed Grafana / Prometheus workspaces, the OpenSearch domain, and
# the IAM roles the OTel collector assumes. The collector's Kubernetes objects
# live in 50-addons-helm, which is the only layer holding cluster credentials.
module "observability" {
  source = "../../modules/observability"

  stack             = var.observability
  oidc_provider_arn = var.oidc_provider_arn
  oidc_issuer       = var.oidc_issuer

  subnet_ids       = var.private_subnets
  opensearch_sg_id = var.opensearch_sg_id

  opensearch_master_username = var.opensearch_master_username
  opensearch_master_password = var.opensearch_master_password
}
