terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}

module "guardrails" {
  source = "../../modules/guardrails"

  environment                 = var.environment
  project                     = var.project
  sizing                      = var.sizing
  allowed_public_access_cidrs = var.allowed_public_access_cidrs
  auth_provider               = var.auth_provider
  observability               = var.observability
}

locals {
  security = module.guardrails.security

  # Verified Access fronts the EKS API only where the endpoint is private-only.
  # In dev the endpoint is public (CIDR-allow-listed), so no AVA plane is built.
  ava_enabled = local.security.verified_access_enabled

  # The `cidr` endpoint forwards to an address range, so it must contain the
  # subnets holding the private EKS API ENIs. Defaults to the whole VPC.
  eks_api_cidr = coalesce(var.eks_api_cidr, var.vpc_cidr)
}

module "verified_access" {
  source = "../../modules/verified-access"
  count  = local.ava_enabled ? 1 : 0

  # Pinned to the physical cluster prefix so the endpoint SG keeps the name the
  # pre-existing configuration used.
  name_prefix = var.cluster_name

  vpc_id              = var.vpc_id
  endpoint_subnet_ids = var.public_subnets
  eks_api_cidr        = local.eks_api_cidr
  kms_key_arn         = var.kms_key_arn

  cidr_endpoints_custom_subdomain = var.ava_custom_subdomain

  oidc_issuer        = var.ava_oidc_issuer
  oidc_client_id     = var.ava_oidc_client_id
  oidc_client_secret = var.ava_oidc_client_secret
  policy_document    = var.ava_policy_document

  logging_enabled           = local.security.verified_access_logging
  log_include_trust_context = local.security.verified_access_log_trust_context

  tags = module.guardrails.common_tags
}

resource "terraform_data" "edge_invariants" {
  input = var.environment

  lifecycle {
    precondition {
      condition     = !local.ava_enabled || var.ava_custom_subdomain != null
      error_message = "Verified Access cidr endpoints require ava_custom_subdomain to be set."
    }

    precondition {
      condition     = !local.ava_enabled || var.ava_oidc_issuer != ""
      error_message = "Verified Access is enabled but no OIDC issuer was supplied."
    }
  }
}
