terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}

locals {
  name = "${var.project}-${var.environment}"

  tags = {
    Project     = var.project
    Environment = var.environment
    Component   = "runner"
    ManagedBy   = "terraform"
  }
}

# Dedicated CMK for the runner's PAT secret and root volume (self-contained).
resource "aws_kms_key" "runner" {
  description             = "${local.name} CI runner encryption (PAT secret + EBS)"
  deletion_window_in_days = 30
  enable_key_rotation     = true
  tags                    = local.tags
}

resource "aws_kms_alias" "runner" {
  name          = "alias/${local.name}-runner"
  target_key_id = aws_kms_key.runner.key_id
}

# ── Isolated runner VPC ──────────────────────────────────────────────────────
module "vpc" {
  source = "../../modules/runner-vpc"

  name     = local.name
  vpc_cidr = var.runner_vpc_cidr
  tags     = local.tags
}

# ── The self-hosted runner (compute + identity) ──────────────────────────────
module "runner" {
  source = "../../modules/gha-runner"

  name          = local.name
  vpc_id        = module.vpc.vpc_id
  subnet_ids    = module.vpc.private_subnet_ids
  github_owner  = var.github_owner
  github_repo   = var.github_repo
  instance_type = var.runner_instance_type

  # Toolchain image repo lives in the bootstrap layer.
  ecr_repository_arn = var.ecr_repository_arn
  ecr_registry       = split("/", var.toolchain_repository_url)[0]

  kms_key_arn = aws_kms_key.runner.arn
  tags        = local.tags
}

# ── Peering to the application VPC (private EKS API reachability) ─────────────
module "peering" {
  source = "../../modules/runner-peering"

  name = local.name

  runner_vpc_id         = module.vpc.vpc_id
  runner_vpc_cidr       = module.vpc.vpc_cidr
  runner_route_table_id = module.vpc.private_route_table_id

  app_vpc_id          = var.app_vpc_id
  app_vpc_cidr        = var.app_vpc_cidr
  app_route_table_ids = var.app_route_table_ids

  cluster_security_group_id  = var.cluster_security_group_id
  cluster_endpoint           = var.cluster_endpoint
  associate_eks_private_zone = var.associate_eks_private_zone
  eks_private_zone_name      = var.eks_private_zone_name

  tags = local.tags
}
