terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.95.0"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
  }
  # Backend + aws provider (default_tags) are generated by Terragrunt.
}

locals {
  tags = {
    Project     = var.project
    Environment = var.environment
    Component   = "rbac"
    ManagedBy   = "terraform"
  }
}

# Cluster-facing provider, configured from the platform layer's remote state
# (same exec-auth pattern as the addons layer). Used to apply the ci-deployer RBAC.
provider "kubectl" {
  host                   = var.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_ca)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name]
  }
}

# EKS access entries, following least privilege principle.
resource "aws_eks_access_entry" "cluster_bootstrap" {
  count = var.create_gated_admin_access_entry ? 1 : 0

  cluster_name  = var.cluster_name
  principal_arn = var.cluster_bootstrap_role_arn
  type          = "STANDARD"
  tags          = local.tags
}

resource "aws_eks_access_policy_association" "cluster_bootstrap_admin" {
  count = var.create_gated_admin_access_entry ? 1 : 0

  cluster_name  = var.cluster_name
  principal_arn = var.cluster_bootstrap_role_arn
  policy_arn    = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"

  access_scope {
    type = "cluster"
  }

  depends_on = [aws_eks_access_entry.cluster_bootstrap]
}

resource "aws_eks_access_entry" "deployer" {
  count = var.map_deployer_access_entry ? 1 : 0

  cluster_name      = var.cluster_name
  principal_arn     = var.tf_apply_role_arn
  type              = "STANDARD"
  kubernetes_groups = [var.deployer_group]
  tags              = local.tags
}

module "ci_deployer_rbac" {
  source = "../../modules/ci-deployer-rbac"
  count  = var.manage_ci_deployer_rbac ? 1 : 0

  manifest_path  = abspath("${path.module}/rbac/ci-deployer.yaml.tpl")
  deployer_group = var.deployer_group

  depends_on = [aws_eks_access_policy_association.cluster_bootstrap_admin]
}

resource "terraform_data" "rbac_invariants" {
  input = var.environment

  lifecycle {
    precondition {
      condition     = !var.map_deployer_access_entry || var.deployer_group != ""
      error_message = "deployer_group is required when mapping the tf-apply access entry to a Kubernetes group."
    }
  }
}
